<a href="https://colab.research.google.com/github/Narottam81/airBnBData/blob/main/AirBnB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
!pip install google-colab

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Airbnb_Open_Data.csv to Airbnb_Open_Data.csv

In [ ]:
filename = list(uploaded.keys())[0]
data = pd.read_csv(filename)
data = pd.read_csv(filename)

In [ ]:
data.head()

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0

In [ ]:
data.columns

Index(['name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Name                    102349 non-null  object
 1   host id                 102599 non-null  int64
 2   host_identity_verified  102310 non-null  object
 3   host name               102193 non-null  object
 4   neighbourhood group     102570 non-null  object
 5   neighbourhood           102583 non-null  object
 6   lat                     102591 non-null  float64
 7   long                    102591 non-null  float64
 8   country                 102067 non-null  object
 9   country code            102468 non-null  object
 10  instant_bookable        102494 non-null  object
 11  cancellation_policy     102523 non-null  object
 12  room type               102599 non-null  object
 13  Construction year       102385 non-null  float64
 14  price                   102352 non-null  object
 15  service fee             102326 non-null  object
 16  minimum nights          102190 non-null  float64
 17  number of reviews       102416 non-null  float64
 18  last review             86706 non-null   object
dtypes: float64(5), int64(1), object(13)
memory usage: 14.9+ MB

In [ ]:
data["license"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: object

In [ ]:
columns_to_keep = ['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'id']

In [ ]:
len(columns_to_keep)
type(columns_to_keep)

list

In [ ]:
len(columns_to_drop)

7

In [ ]:
#Method for dropping columns
data.columns = [col.lower() for col in data.columns]
data = data[[col for col in data.columns if col in columns_to_keep]]
columns_to_drop_lower = [col.lower() for col in columns_to_drop]
data.columns = [col.lower() for col in data.columns]
columns_to_drop_existing = [col for col in columns_to_drop_lower if col in data.columns]
data.drop(columns=columns_to_drop_existing, inplace=True)

columns_to_keep_lower = [col.lower() for col in columns_to_keep]
data_columns_lower = [col.lower() for col in data.columns]
selected_columns = [data.columns[data_columns_lower.index(col)] for col in columns_to_keep_lower if col in data_columns_lower]
data = data[selected_columns]
data.columns

Index(['host id', 'host_identity_verified', 'host name', 'neighbourhood group',
       'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type', 'price',
       'service fee', 'minimum nights', 'number of reviews'],
      dtype='object')

In [ ]:
data.shape

(102058, 18)

In [ ]:
data.columns

Index(['name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews'],
      dtype='object')

In [ ]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews'],
      dtype='object')

In [ ]:
new_columns_names = []
for i in data.columns:
  new_columns_names.append(i.upper())

In [ ]:
new_dataframe_to_modify = data.copy()
new_dataframe_to_modify.columns = new_columns_names

In [ ]:
new_dataframe_to_modify.columns

Index(['HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME', 'NEIGHBOURHOOD GROUP',
       'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY', 'COUNTRY CODE',
       'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE', 'PRICE',
       'SERVICE FEE', 'MINIMUM NIGHTS', 'NUMBER OF REVIEWS'],
      dtype='object')

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.drop_duplicates(inplace = True)
data.duplicated().sum()

np.int64(0)

In [ ]:
data.isna().sum()

host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
price                     0
service fee               0
minimum nights            0
number of reviews         0
dtype: int64

In [ ]:
data.dropna(inplace=True)

In [ ]:
data["host_identity_verified"].str.upper()

0         UNCONFIRMED
1            VERIFIED
3         UNCONFIRMED
4            VERIFIED
5            VERIFIED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 99731, dtype: object

In [ ]:
data["host_identity_verified"] = data["host_identity_verified"].str.upper()
data["instant_bookable"].apply(lambda x:1 if x == True else 0)
data["instant_bookable"] = data["instant_bookable"].apply(lambda x:1 if x == True else 0)
data.reset_index(inplace = True)

In [ ]:
data["price"].head(3)
data["price"].str.replace("$","")
data["price"]= data["price"].str.replace("$","")
data["price"].str.replace(",", "")
data["prince"] =data["price"].str.replace(",","")
data["prince"].astype(int)

0         966
1         142
2         368
3         204
4         577
         ...
99726     822
99727     455
99728    1078
99729     103
99730     982
Name: prince, Length: 99731, dtype: int64

In [ ]:
data.to_csv("Cleaned_AIRNB_Data")

In [ ]:
pd.read_csv("Cleaned_AIRNB_Data")

,Unnamed: 0,index,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,price,service fee,minimum nights,number of reviews,prince
0,0,0,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,966,$193,10.0,9.0,966
1,1,1,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,142,$28,30.0,45.0,142
2,2,3,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1,moderate,Entire home/apt,368,$74,30.0,270.0,368
3,3,4,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,204,$41,10.0,9.0,204
4,4,5,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,577,$115,3.0,74.0,577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99726,99726,102029,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,822,$164,1.0,9.0,822
99727,99727,102030,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,455,$91,4.0,36.0,455
99728,99728,102031,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,"1,078",$216,1.0,58.0,1078
99729,99729,102032,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,103,$21,7.0,40.0,103
99730,99730,102040,56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,982,$196,1.0,239.0,982

In [ ]:
data.to_csv("Cleaned_AIRNB_Data_wo_Index.csv", index=False)
files.download("Cleaned_AIRNB_Data_wo_Index.csv")